# Generated by Django 5.2.6 on 2025-09-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProcesado',
            fields=[
                ('id_pedido_original', models.IntegerField(help_text='ID original del pedido de entrada', primary_key=True, serialize=False)),
                ('hash_pedido', models.CharField(help_text='Hash SHA-256 del pedido procesado', max_length=64, unique=True)),
                ('cliente', models.CharField(max_length=255)),
                ('detalle_completo', models.JSONField(help_text='JSON con la lista de productos enriquecidos')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_procesado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
