# Generated by Django 5.2.6 on 2025-09-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('task_id', models.CharField(help_text='ID único de la tarea de Huey', max_length=36, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('STARTED', 'Iniciada'), ('SUCCESS', 'Completada'), ('ERROR', 'Fallida')], max_length=10)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
