# Generated by Django 5.2.6 on 2025-09-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_app', '0002_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='pedido_id',
            field=models.IntegerField(blank=True, help_text='ID del pedido procesado asociado a esta tarea', null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='worker_hostname',
            field=models.CharField(blank=True, help_text='Hostname del worker que ejecutó la tarea', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task_id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
