# Generated by Django 5.2.6 on 2025-09-25 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_app', '0003_taskhistory_pedido_id_taskhistory_worker_hostname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='pedido_id',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_history', to='pedidos_app.pedidoprocesado'),
        ),
    ]
